/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tienda;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;

/**
 *
 * @author franc
 */
public class FmrPrincipal extends javax.swing.JFrame implements ActionListener {

    ArrayList<Producto> Lista = new ArrayList<>();
    public FmrPrincipal() {
        initComponents();
        btnAgregar.addActionListener(this);
        btnMostrar.addActionListener(this);
        btnCalcular.addActionListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnMostrar = new javax.swing.JButton();
        btnCalcular = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPanel = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Nombre:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 30, 70, 16);

        jLabel2.setText("Precio:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 70, 70, 16);

        jLabel3.setText("Cantidad");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 110, 70, 16);
        getContentPane().add(txtNombre);
        txtNombre.setBounds(140, 30, 94, 22);
        getContentPane().add(txtPrecio);
        txtPrecio.setBounds(140, 70, 94, 22);
        getContentPane().add(txtCantidad);
        txtCantidad.setBounds(140, 110, 90, 22);

        btnAgregar.setText("Agregar");
        getContentPane().add(btnAgregar);
        btnAgregar.setBounds(120, 160, 75, 23);

        btnMostrar.setText("Mostrar");
        getContentPane().add(btnMostrar);
        btnMostrar.setBounds(210, 160, 72, 23);

        btnCalcular.setText("Calcular valor total ");
        getContentPane().add(btnCalcular);
        btnCalcular.setBounds(300, 160, 140, 23);

        txtPanel.setColumns(20);
        txtPanel.setRows(5);
        jScrollPane1.setViewportView(txtPanel);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(50, 210, 460, 270);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FmrPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FmrPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FmrPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FmrPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FmrPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextArea txtPanel;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        if(e.getSource()==btnAgregar){
            Producto nuevoProducto = new Producto();
            Agregar(nuevoProducto);
        }else if(e.getSource()==btnMostrar){
            Mostrar();
        }else if(e.getSource()==btnCalcular){
            totalInventario();
        }
        
    }
    public void Agregar(Producto producto){
       
        producto.setNombre(txtNombre.getText());
        producto.setCantidad(Integer.parseInt(txtCantidad.getText()));
        producto.setPrecio(Integer.parseInt(txtPrecio.getText()));
        Lista.add(producto);
        
    }
    
    public void Mostrar(){
        txtPanel.setText("");
        for(Producto p : Lista){
            txtPanel.append(p.toString());
        }
    }
    
    public void totalInventario(){
        txtPanel.setText("");
        int total = 0;
        for(Producto p : Lista){
           
           total += p.getCantidad() * p.getPrecio();
        }
        txtPanel.append("Total De Inventario: Q"+total);
    }
}


